export const MOCK_MARKET_LISTINGS = [
  {
    id: 101,
    recipe: {
      id: 11,
      title: '해물 된장찌개',
      thumbnailUrl: '/images/marketplace/seafood-doenjang-stew.jpg',
      difficulty: 'EASY',
      category: 'KOREAN',
      summary: '해산물을 듬뿍 넣어 시원하게 끓인 된장찌개입니다.',
      minPrice: 4,
    },
    seller: { id: 1, nickname: '미쓰손' },
    listingType: 'SALE',
    price: 4,
    initialQuantity: 5,
    remainingQuantity: 3,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-09-04T01:00:00.000Z',
    updatedAt: '2026-09-04T01:00:00.000Z',
  },
  {
    id: 102,
    recipe: {
      id: 12,
      title: '고추장 닭날개 조림',
      thumbnailUrl: '/images/marketplace/gochujang-chicken-wings.jpg',
      difficulty: 'NORMAL',
      category: 'KOREAN',
      summary: '매콤달콤한 고추장 양념으로 윤기 있게 조린 닭날개입니다.',
      minPrice: 5,
    },
    seller: { id: 2, nickname: '랍스타' },
    listingType: 'SALE',
    price: 5,
    initialQuantity: 3,
    remainingQuantity: 2,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-09-03T06:30:00.000Z',
    updatedAt: '2026-09-03T06:30:00.000Z',
  },
  {
    id: 103,
    recipe: {
      id: 13,
      title: '새우 빠에야',
      thumbnailUrl: '/images/marketplace/seafood-paella.jpg',
      difficulty: 'HARD',
      category: 'WESTERN',
      summary: '새우와 홍합을 올려 풍성하게 완성한 해산물 빠에야입니다.',
      minPrice: 7,
    },
    seller: { id: 3, nickname: '프로한식러' },
    listingType: 'SALE',
    price: 7,
    initialQuantity: 4,
    remainingQuantity: 1,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-09-02T10:10:00.000Z',
    updatedAt: '2026-09-02T10:10:00.000Z',
  },
  {
    id: 104,
    recipe: {
      id: 14,
      title: '말차 딸기 케이크',
      thumbnailUrl: '/images/marketplace/matcha-strawberry-cake.jpg',
      difficulty: 'MASTER',
      category: 'HOME_BAKING',
      summary: '말차 시트와 생딸기 크림을 겹겹이 쌓은 케이크입니다.',
      minPrice: 9,
    },
    seller: { id: 4, nickname: '유디' },
    listingType: 'SALE',
    price: 9,
    initialQuantity: 2,
    remainingQuantity: 0,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'SOLD_OUT',
    createdAt: '2026-09-01T03:20:00.000Z',
    updatedAt: '2026-09-04T02:00:00.000Z',
  },
  {
    id: 105,
    recipe: {
      id: 15,
      title: '바지락 된장찌개',
      thumbnailUrl: '/images/marketplace/seafood-doenjang-stew.jpg',
      difficulty: 'NORMAL',
      category: 'KOREAN',
      summary: '바지락 육수의 감칠맛을 살린 구수한 된장찌개입니다.',
      minPrice: 3,
    },
    seller: { id: 5, nickname: '집밥고수' },
    listingType: 'SALE',
    price: 3,
    initialQuantity: 4,
    remainingQuantity: 4,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-31T12:00:00.000Z',
    updatedAt: '2026-08-31T12:00:00.000Z',
  },
  {
    id: 106,
    recipe: {
      id: 16,
      title: '매콤 닭날개 구이',
      thumbnailUrl: '/images/marketplace/gochujang-chicken-wings.jpg',
      difficulty: 'EASY',
      category: 'FUSION',
      summary: '오븐으로 간단하게 완성하는 매콤한 닭날개 구이입니다.',
      minPrice: 4,
    },
    seller: { id: 6, nickname: '오늘뭐먹지' },
    listingType: 'SALE',
    price: 4,
    initialQuantity: 3,
    remainingQuantity: 2,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-30T09:45:00.000Z',
    updatedAt: '2026-08-30T09:45:00.000Z',
  },
  {
    id: 107,
    recipe: {
      id: 17,
      title: '해산물 볶음밥',
      thumbnailUrl: '/images/marketplace/seafood-paella.jpg',
      difficulty: 'HARD',
      category: 'CHINESE',
      summary: '각종 해산물과 고슬고슬한 밥을 센 불에 볶은 요리입니다.',
      minPrice: 6,
    },
    seller: { id: 7, nickname: '웍마스터' },
    listingType: 'SALE',
    price: 6,
    initialQuantity: 5,
    remainingQuantity: 5,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-29T04:15:00.000Z',
    updatedAt: '2026-08-29T04:15:00.000Z',
  },
  {
    id: 108,
    recipe: {
      id: 18,
      title: '딸기 말차 컵케이크',
      thumbnailUrl: '/images/marketplace/matcha-strawberry-cake.jpg',
      difficulty: 'MASTER',
      category: 'HOME_BAKING',
      summary: '쌉싸름한 말차와 상큼한 딸기를 조합한 컵케이크입니다.',
      minPrice: 8,
    },
    seller: { id: 8, nickname: '베이킹소녀' },
    listingType: 'SALE',
    price: 8,
    initialQuantity: 3,
    remainingQuantity: 1,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-28T08:00:00.000Z',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 109,
    recipe: {
      id: 19,
      title: '간장 닭날개 구이',
      thumbnailUrl: '/images/marketplace/gochujang-chicken-wings.jpg',
      difficulty: 'NORMAL',
      category: 'JAPANESE',
      summary: '달콤짭짤한 간장 양념을 입혀 노릇하게 구운 닭날개입니다.',
      minPrice: 5,
    },
    seller: { id: 9, nickname: '간장요리사' },
    listingType: 'SALE',
    price: 5,
    initialQuantity: 4,
    remainingQuantity: 3,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-27T11:30:00.000Z',
    updatedAt: '2026-08-27T11:30:00.000Z',
  },
  {
    id: 110,
    recipe: {
      id: 20,
      title: '해산물 크림 리조또',
      thumbnailUrl: '/images/marketplace/seafood-paella.jpg',
      difficulty: 'HARD',
      category: 'WESTERN',
      summary: '부드러운 크림과 해산물의 풍미를 담은 리조또입니다.',
      minPrice: 7,
    },
    seller: { id: 10, nickname: '리조또장인' },
    listingType: 'SALE',
    price: 7,
    initialQuantity: 5,
    remainingQuantity: 2,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-26T05:20:00.000Z',
    updatedAt: '2026-08-26T05:20:00.000Z',
  },
  {
    id: 111,
    recipe: {
      id: 21,
      title: '말차 딸기 타르트',
      thumbnailUrl: '/images/marketplace/matcha-strawberry-cake.jpg',
      difficulty: 'MASTER',
      category: 'HOME_BAKING',
      summary: '진한 말차 크림과 생딸기를 올린 바삭한 타르트입니다.',
      minPrice: 10,
    },
    seller: { id: 11, nickname: '타르트연구소' },
    listingType: 'SALE',
    price: 10,
    initialQuantity: 3,
    remainingQuantity: 1,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-25T15:40:00.000Z',
    updatedAt: '2026-08-25T15:40:00.000Z',
  },
  {
    id: 112,
    recipe: {
      id: 22,
      title: '얼큰 해물 전골',
      thumbnailUrl: '/images/marketplace/seafood-doenjang-stew.jpg',
      difficulty: 'EASY',
      category: 'KOREAN',
      summary: '여러 가지 해산물을 넣고 얼큰하게 끓인 전골입니다.',
      minPrice: 6,
    },
    seller: { id: 12, nickname: '국물대장' },
    listingType: 'SALE',
    price: 6,
    initialQuantity: 2,
    remainingQuantity: 0,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'SOLD_OUT',
    createdAt: '2026-08-24T02:10:00.000Z',
    updatedAt: '2026-08-26T09:00:00.000Z',
  },
  {
    id: 113,
    recipe: {
      id: 23,
      title: '고추장 치킨 파스타',
      thumbnailUrl: '/images/marketplace/gochujang-chicken-wings.jpg',
      difficulty: 'NORMAL',
      category: 'FUSION',
      summary: '고추장의 매콤한 맛을 더한 치킨 파스타입니다.',
      minPrice: 6,
    },
    seller: { id: 13, nickname: '퓨전키친' },
    listingType: 'SALE',
    price: 6,
    initialQuantity: 5,
    remainingQuantity: 4,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-23T07:50:00.000Z',
    updatedAt: '2026-08-23T07:50:00.000Z',
  },
  {
    id: 114,
    recipe: {
      id: 24,
      title: '중화 해물 덮밥',
      thumbnailUrl: '/images/marketplace/seafood-paella.jpg',
      difficulty: 'HARD',
      category: 'CHINESE',
      summary: '불향을 입힌 해산물 소스를 밥 위에 올린 덮밥입니다.',
      minPrice: 5,
    },
    seller: { id: 14, nickname: '불맛고수' },
    listingType: 'SALE',
    price: 5,
    initialQuantity: 4,
    remainingQuantity: 2,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-22T13:25:00.000Z',
    updatedAt: '2026-08-22T13:25:00.000Z',
  },
  {
    id: 115,
    recipe: {
      id: 25,
      title: '말차 딸기 라떼',
      thumbnailUrl: '/images/marketplace/matcha-strawberry-cake.jpg',
      difficulty: 'EASY',
      category: 'BEVERAGE',
      summary: '말차와 딸기 우유를 층층이 담아 완성한 음료입니다.',
      minPrice: 3,
    },
    seller: { id: 15, nickname: '홈카페유디' },
    listingType: 'SALE',
    price: 3,
    initialQuantity: 3,
    remainingQuantity: 3,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-21T04:35:00.000Z',
    updatedAt: '2026-08-21T04:35:00.000Z',
  },
  {
    id: 116,
    recipe: {
      id: 26,
      title: '일본식 해물 된장국',
      thumbnailUrl: '/images/marketplace/seafood-doenjang-stew.jpg',
      difficulty: 'MASTER',
      category: 'JAPANESE',
      summary: '해산물 육수와 일본식 된장을 사용해 깊게 끓인 국입니다.',
      minPrice: 8,
    },
    seller: { id: 16, nickname: '미소마스터' },
    listingType: 'SALE',
    price: 8,
    initialQuantity: 4,
    remainingQuantity: 1,
    wantedDifficulty: null,
    wantedCategory: null,
    wantedDescription: null,
    status: 'ON_SALE',
    createdAt: '2026-08-20T10:05:00.000Z',
    updatedAt: '2026-08-20T10:05:00.000Z',
  },
]
